### ISSUE TITLE
StringExtensions.swift swift 4 

### ISSUE THREAD

**Issue by Abdulaziz-almoshen** [mehulparmar4ever/GoogleMapDemo#1]
Can you convert the StringExtensions.swift to swift 4 please ? I like your work!!

**Comment by mehulparmar4ever** [comment]
Ya sure, will update you soon.

**Comment by mehulparmar4ever** [comment]
I have removed StringExtensions.swift file. It is not necessory, everything else is updated to swift .
;-)
